version: '2'

services:
  webapp:
    image: webapp
    build:
      context: ./WebApp
      dockerfile: Dockerfile

  webapi:
    image: webapi
    build:
      context: ./WebApi
      dockerfile: Dockerfile
